spring:
  cloud:
    aws:
      credentials:
        access_key: ${AWS_ACCESS_KEY}
        secret_key: ${AWS_SECRET_KEY}
      region: ${AWS_REGION}
app:
  config:
    messaging:
      queues:
        order-payment: order-payment
        order-finished: order-finished